apiVersion: v1
appVersion: 0.0.3
description: cert-manager webhook solver for ACME DNS01 challenge via DNSimple
name: cert-manager-webhook-dnsimple
version: 0.0.3
home: https://github.com/neoskop/cert-manager-webhook-dnsimple
sources:
  - https://github.com/neoskop/cert-manager-webhook-dnsimple
maintainers:
  - name: Arne Diekmann
    email: diekmann@neoskop.de
    url: https://www.neoskop.de
